### ISSUE TITLE
How many regressors should the aCompCor model include? (5 or 10?)

### ISSUE THREAD

**Issue by amnsbr** [brainlife/app-bold-time-series#1]
Hi,

According to [Parkes et al.](https://www.sciencedirect.com/science/article/pii/S1053811917310972?via%3Dihub) the aCompCor model includes the leading 5 PCs for each tissue type (WM and CSF), yielding 10 confound regressors. Therefore, and for example using the "24aCompCor" option (which corresponds to model no. 7 of Parkes et al.), there should be a total of 34 regressors. However, the implementation here gets the first 5 aCompCor components of the combined mask (if confounds.json exists) and for "24aCompCor" returns 29 regressors (24 motion parameters + 5 aCompCor + 1 linear trend). Am I understanding this correctly? Is there a reason that the app's implementation differs from the model in the paper? Thanks in advance.

**Comment by francopestilli** [comment]
hi @amnsbr  thanks, perhaps @faskowit can respond here?

**Comment by faskowit** [comment]
Indeed you are understanding it correctly @amnsbr!  In earlier versions, fmriprep used to only compute aCompCor on combined 'wm+csf' masks, for the purpose of reproducibility/reliability, to make sure that the mask had a substantial number of voxels in it to accurately do the decomposition. This code was first written when that was the case.  Now, I do believe that fmriprep supports comined, wm, and csf masks (see here, maybe: https://github.com/nipreps/fmriprep/commit/896f6f8e44cf1ad693e90770fdce85d596dcd728) but this code still runs on the combined masks. For what it's worth, the original aCompCor paper used the combined mask too for aCompCor: 10.1016/j.neuroimage.2007.04.042

**Comment by amnsbr** [comment]
Yes. That makes sense then. Thank you very much for making it clear.
